### ISSUE TITLE
problem when install graphite-kenshin api "needs_pytest " invalid syntax

### ISSUE THREAD

**Issue by luckywarrior** [douban/graphite-kenshin#5]
File "setup.py", line 7
    needs_pytest = {'pytest', 'test', 'ptr'}.intersection(sys.argv)
                            ^
SyntaxError: invalid syntax

**Comment by zzl0** [comment]
The syntax for set literals ({1,2,3} is introduced in [Python 2.7](https://docs.python.org/3/whatsnew/2.7.html#python-3-1-features)

**Comment by zzl0** [comment]
@luckywarrior Can you upgrade your Python version?

**Comment by luckywarrior** [comment]
yes, i update to 2.7.12,but it says "No matching distribution found for Twisted==13.1 (from -r requirements.txt (line 4))",result in Twisted couldn't be installed

**Comment by luckywarrior** [comment]
download numpy-1.12.1rc1.zip  and Twisted-17.1.0 to install can solved the problem

**Comment by zzl0** [comment]
```
╰─± pip install -r requirements.txt --no-cache-dir
Requirement already satisfied: Cython in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: numpy==1.8.0 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: zope.interface==4.1.1 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Collecting Twisted==13.1 (from -r requirements.txt (line 4))
  Downloading Twisted-13.1.0.tar.bz2 (2.7MB)
    6% |██▏                             | 184kB 35kB/s eta 0:01:10^
```
@luckywarrior Twisted 13.1.0 seems good to me.
