### ISSUE TITLE
kenshin支持单机多盘吗?

### ISSUE THREAD

**Issue by xianhuawei** [douban/graphite-kenshin#9]
类似这种 配置后能跑起来 但graphite_api取不了数据
rurouni.conf 

[cache] 
CONF_DIR = /etc/kenshin 
PID_DIR = /var/run/kenshin 
LINE_RECEIVER_INTERFACE = 
PICKLE_RECEIVER_INTERFACE = 
CACHE_QUERY_INTERFACE = 
LOG_UPDATES = True 
MAX_CREATES_PER_MINUTE = 1000 
NUM_ALL_INSTANCE = 6 
DEFAULT_WAIT_TIME = 1 

[cache:0] 
LINE_RECEIVER_PORT = 2000 
PICKLE_RECEIVER_PORT = 3000 
CACHE_QUERY_PORT = 4000 
LOCAL_DATA_DIR = /data0/kenshin/data 
LOCAL_LINK_DIR = /data0/kenshin/link 
LOG_DIR = /data0/kenshin/log

[cache:1] 
LINE_RECEIVER_PORT = 2001 
PICKLE_RECEIVER_PORT = 3001 
CACHE_QUERY_PORT = 4001 
LOCAL_DATA_DIR = /data1/kenshin/data 
LOCAL_LINK_DIR = /data1/kenshin/link 
LOG_DIR = /data1/kenshin/log

[cache:2] 
LINE_RECEIVER_PORT = 2002 
PICKLE_RECEIVER_PORT = 3002 
CACHE_QUERY_PORT = 4002 
LOCAL_DATA_DIR = /data2/kenshin/data 
LOCAL_LINK_DIR = /data2/kenshin/link 
LOG_DIR = /data2/kenshin/log

[cache:3] 
LINE_RECEIVER_PORT = 2003 
PICKLE_RECEIVER_PORT = 3003 
CACHE_QUERY_PORT = 4003 
LOCAL_DATA_DIR = /data3/kenshin/data 
LOCAL_LINK_DIR = /data3/kenshin/link 
LOG_DIR = /data3/kenshin/log

[cache:4] 
LINE_RECEIVER_PORT = 2004 
PICKLE_RECEIVER_PORT = 3004 
CACHE_QUERY_PORT = 4004 
LOCAL_DATA_DIR = /data4/kenshin/data 
LOCAL_LINK_DIR = /data4/kenshin/link 
LOG_DIR = /data4/kenshin/log

[cache:5] 
LINE_RECEIVER_PORT = 2005 
PICKLE_RECEIVER_PORT = 3005 
CACHE_QUERY_PORT = 4005 
LOCAL_DATA_DIR = /data5/kenshin/data 
LOCAL_LINK_DIR = /data5/kenshin/link 
LOG_DIR = /data5/kenshin/log

graphite-api.yaml

search_index: /data0/kenshin/index 
time_zone: 'Asia/Shanghai' 
finders: 
 - kenshin_api.KenshinFinder 
kenshin: 
  directories:
  - /data0/kenshin/link/0
  - /data1/kenshin/link/1
  - /data2/kenshin/link/2
  - /data3/kenshin/link/3
  - /data4/kenshin/link/4
  - /data5/kenshin/link/5
  carbonlink_hosts:
  - 10.3.136.211:4000:0
  - 10.3.136.211:4001:1
  - 10.3.136.211:4002:2
  - 10.3.136.211:4003:3
  - 10.3.136.211:4004:4
  - 10.3.136.211:4005:5
 
  memcached: 
    expire_time: 20 
    hosts: 
    - 10.3.136.211:11211 
functions: 
 - graphite_api.functions.SeriesFunctions 
 - graphite_api.functions.PieFunctions 
 - kenshin_api.functions.SeriesFunctions

**Comment by zzl0** [comment]
@xianhuawei Kenshin 支持单机多盘的。从配置文件没有看出什么问题。你那边有报什么错误吗？另外，想确认下你可以在本地按照 README 的步骤运行 kenshin、graphite-api、carbon-c-relay，并且正常数据吗？

**Comment by xianhuawei** [comment]
单机的时候正常 能出图 
但改成多台后不行

咨询下 graphite-api.yaml 怎么配置其中的directories 让 graphite-api 可以读取多台机器上的kenshin啊

**Comment by zzl0** [comment]
@xianhuawei 所以单机多盘的问题好了，是吗？

如果你想了解数据分布在多台机器的情况，你需要查看 graphie-api 关于 cluster 的支持，这个是在 graphite-api 层做跨机器的访问的。我在 Douban 的时候，我们所有数据是在一台机器上的（会有 Replica 节点）。所以对于跨机器的部署，我没有直接经验。另外，建议使用 SSD，一台机器可以支撑百万级别指标的。

**Comment by xianhuawei** [comment]
对 单机多盘的好了

graphie-api 没有找到跨机器的配置 这个项目也没找到

单台百万是多少个ssd盘啊?

**Comment by xianhuawei** [comment]
Replica 的功能是通过carbon-c-relay来做的吗？

**Comment by camper42** [comment]
1. 目前是 3 台机器，每台一块 1T SSD (ioutil 5%左右)，16 个 rurouni instance (130M RSS/instance)

2. https://github.com/brutasse/graphite-api

3. carbon-c-relay 将收到的指标同时向多个点发送，可以参照本项目 README 的图

**Comment by xianhuawei** [comment]
谢谢2位

基本明白了
